# ----------------------------------------------------------------------------------------------------
# Pipeline to scan/build an app upon Pull Request
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
# FYI - Set a required branch policy to run this on every check to main
# ----------------------------------------------------------------------------------------------------
# trigger:
#   - none
pr:
  - main

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.LZ.Secrets
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
      - template: pipes/templates/scan-code-template.yml
        parameters:
          environmentCode: 'DEV'
          runMSDevSecOpsScan: true
          runGHASScan: false

  - template: pipes/build-deploy-app-pipe.yml
    parameters:
      pushToACR: false
      deployAction: 'build-only'
      apps: [ 
        { containerAppName: 'ui',  acrAppName: 'chatui',  projectFolderName: 'src/website/chatui', port: '8080' }
      ] 
