# ----------------------------------------------------------------------------------------------------
# Code Scanning Template
# ----------------------------------------------------------------------------------------------------
# GitHub Advanced Security For Azure DevOps
# To enable this, you must enable GHAzDO for this repository in your Azure DevOps Project
# ----------------------------------------------------------------------------------------------------
# Microsoft Secure DevOps Scan
# To enable this, you must add Azure DevOps Extension to your Azure DevOps Organization
# See https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environmentCode
    default: 'DV'
  - name: runGHASScan
    default: 'false'
  - name: runMSDevSecOpsScan
    default: 'false'
  - name: continueOnScanError
    default: 'true'
  - name: codeSection
    default: 'app'

# ----------------------------------------------------------------------------------------------------
jobs:
  - deployment: CodeScanDeployment${{parameters.codeSection}}
    displayName: Initialize Code Scans ${{parameters.codeSection}}
    environment: ${{ parameters.environmentCode }}

  # ----------------------------------------------------------------------------------------------------
  - ${{ if and(eq(lower(parameters.runGHASScan), 'false'), eq(lower(parameters.runMSDevSecOpsScan), 'false')) }}:
      - job: NoScanJob
        displayName: No Scan Requested
        steps:
          - bash: |
              echo "No MS DevOps or GHAS scan requested!"
            displayName: 'Stub Step'

  # ----------------------------------------------------------------------------------------------------
  - ${{ if eq(lower(parameters.runGHASScan), 'true') }}:
      - job: GHASScanJob${{parameters.codeSection}}
        displayName: GHAS Scan Job ${{parameters.codeSection}}
        variables:
          # Bring in environment common variable file
          - template: ../../vars/var-common.yml
          - ${{ if eq(lower(parameters.codeSection), 'app') }}:
              - template: ../../vars/var-source-location-app.yml
          - ${{ if eq(lower(parameters.codeSection), 'console') }}:
              - template: ../../vars/var-source-location-console.yml
          # Bring in environment specific variable files
          - ${{ if eq(lower(parameters.environmentCode), 'dv') }}:
              - template: ../../vars/var-dv.yml
          - ${{ if eq(lower(parameters.environmentCode), 'ts') }}:
              - template: ../../vars/var-ts.yml
          - ${{ if eq(lower(parameters.environmentCode), 'pd') }}:
              - template: ../../vars/var-pd.yml
        steps:
          # Very basic simple example that sometimes works...
          # - task: AdvancedSecurity-Codeql-Init@1
          #   inputs:
          #     languages: 'csharp'
          # - task: DotNetCoreCLI@2
          #   inputs:
          #     command: 'restore'
          # - task: AdvancedSecurity-Dependency-Scanning@1
          # - task: AdvancedSecurity-Codeql-Autobuild@1
          # - task: AdvancedSecurity-Codeql-Analyze@1
          # - task: AdvancedSecurity-Publish@1

          - task: CmdLine@2
            displayName: 'Display Variables and Tree'
            inputs:
              script: |
                echo "parameters.continueOnScanError=${{ parameters.continueOnScanError }}"
                echo "parameters.codeSection=${{ parameters.codeSection }}"
                echo "appFolderName=$(appFolderName)"
                echo "appSolutionName=$(appSolutionName)"
                echo "appProjectName=$(appProjectName)"
                echo "appProjectFolderName=$(appProjectFolderName)"
                echo "workingDirectoryInfra=$(workingDirectoryInfra)"
                echo "workingDirectoryIgnore=$(workingDirectoryIgnore)"
                echo "Project Path: $(Build.SourcesDirectory)/$(appProjectFolderName)/*.$(appProjectExtension)"
                echo "Build.SourcesDirectory=$(Build.SourcesDirectory)"
                echo "----------------------------------------"
                echo "##[group]Display All Environment Variables:"
                printenv | sort
                echo "##[endgroup]"
                echo "------------------------------------------------"
                echo "##[group]Directory of Project Files: $(Build.SourcesDirectory)/$(appProjectFolderName)"
                tree -L 4 $(Build.SourcesDirectory)/$(appProjectFolderName)
                echo "##[endgroup]"
                echo "------------------------------------------------"
                echo "##[group]Directory of Full Staging Directory: $(Build.SourcesDirectory)"
                tree -L 4 $(Build.SourcesDirectory)
                echo "##[endgroup]"
            continueOnError: true

          - task: AdvancedSecurity-Codeql-Init@1
            displayName: GHAS Init
            inputs:
              languages: 'csharp'
              querysuite: security-extended
            #   sourcesfolder: $(appProjectFolderName)
            #   codeqlpathstoinclude: $(appProjectFolderName)
            #   codeqlpathstoignore: $(workingDirectoryIgnore)

          # You may be able to use autobuild, but I replaced it with specific build steps in this pipeline
          # - ${{ if eq(lower(variables.appProjectExtension), 'csproj') }}:
          #   - task: AdvancedSecurity-Codeql-Autobuild@1
          #     displayName: GHAS AutoBuild
          #     continueOnError: ${{ eq(parameters.continueOnScanError, 'true') }}

          # If AutoBuild has failed, review the following troubleshooting steps.
          # 1.  Verify that the language is set properly.
          # 2.  Ensure that any configuration or dependencies are installed prior to the AutoBuild task.
          # 3.  AutoBuild may not be suitable for your project. Replace the AutoBuild task in your pipeline with the normal build tasks
          #     to build your project. This will give you more control over the build steps.

          - task: DotNetCoreCLI@2
            displayName: 'Restore project'
            inputs:
              command: 'restore'
              projects: '$(Build.SourcesDirectory)/$(appProjectFolderName)/*.$(appProjectExtension)'

          - ${{ if eq(lower(variables.appProjectExtension), 'csproj') }}:
              - task: DotNetCoreCLI@2
                displayName: Build CS Project
                inputs:
                  projects: '$(Build.SourcesDirectory)/$(appProjectFolderName)/*.$(appProjectExtension)'
                  arguments: '--output publish_output --configuration Release'

          - ${{ if eq(lower(variables.appProjectExtension), 'sqlproj') }}:
              - task: VSBuild@1
                displayName: Build DacPac Project
                inputs:
                  solution: '$(appFolderName)/$(appSolutionName).sln'
                  platform: 'Any CPU'
                  configuration: 'Release'

          - task: AdvancedSecurity-Dependency-Scanning@1
            displayName: GHAS Dependency Scanning
            continueOnError: ${{ eq(parameters.continueOnScanError, 'true') }}

          - task: AdvancedSecurity-Codeql-Analyze@1
            displayName: GHAS Analyze
            continueOnError: ${{ eq(parameters.continueOnScanError, 'true') }}

          - task: AdvancedSecurity-Publish@1
            displayName: GHAS Publish
            continueOnError: ${{ eq(parameters.continueOnScanError, 'true') }}

  # ----------------------------------------------------------------------------------------------------
  - ${{ if eq(lower(parameters.runMSDevSecOpsScan), 'true') }}:
      - job: DevSecOpsScanJob${{parameters.codeSection}}
        displayName: DevSecOps Scan Job ${{parameters.codeSection}}
        variables:
          # Bring in environment common variable file
          - template: ../../vars/var-common.yml
          - ${{ if eq(lower(parameters.codeSection), 'app') }}:
              - template: ../../vars/var-source-location-app.yml
          - ${{ if eq(lower(parameters.codeSection), 'console') }}:
              - template: ../../vars/var-source-location-console.yml
          # Bring in environment specific variable files
          - ${{ if eq(lower(parameters.environmentCode), 'dv') }}:
              - template: ../../vars/var-dv.yml
          - ${{ if eq(lower(parameters.environmentCode), 'ts') }}:
              - template: ../../vars/var-ts.yml
          - ${{ if eq(lower(parameters.environmentCode), 'pd') }}:
              - template: ../../vars/var-pd.yml
        steps:
          - bash: |
              echo "parameters.runMSDevSecOpsScan=${{parameters.runMSDevSecOpsScan}}"
              echo "parameters.continueOnScanError=${{parameters.continueOnScanError}}"
              echo "sourceVariableFile=$(sourceVariableFile)"
              echo "appProjectFolderName=$(appProjectFolderName)"
              echo "workingDirectoryInfra=$(workingDirectoryInfra)"
              echo "workingDirectoryIgnore=$(workingDirectoryIgnore)"
              echo "----------------------------------------"
              echo "##[group]Display All Environment Variables:"
              printenv | sort
              echo "##[endgroup]"
              echo "----------------------------------------"
              echo "##[group]Directory Listing for $(Pipeline.Workspace)"
              tree -L 4 $(Pipeline.Workspace)
              echo "##[endgroup]"
            displayName: 'Display Variables'
            continueOnError: true

          - task: UseDotNet@2
            displayName: 'Use dotnet 8.0'
            inputs:
              version: 8.0.x

          - task: MicrosoftSecurityDevOps@1
            displayName: 'Run Microsoft Security DevOps'
            continueOnError: true

          - script: |
              echo "Installing additional security tools..."
              pip install safety semgrep
            displayName: 'Install Additional Security Tools'
            continueOnError: true

          - script: |
              echo "Scanning for known vulnerabilities in dependencies..."
              if [ -f "requirements.txt" ]; then
                safety check -r requirements.txt --json --output safety-report.json || echo "Vulnerability scan completed with findings"
                cat safety-report.json || echo "No safety report generated"
              else
                echo "No requirements.txt found, skipping dependency scan"
              fi
            displayName: 'Dependency Vulnerability Scan (Safety)'
            continueOnError: true

          - script: |
              echo "Scanning for secrets and credentials..."
              if find . -name "*.py" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" | head -1 > /dev/null; then
                semgrep --config=auto --json --output=semgrep-report.json . || echo "Secret scan completed"
                cat semgrep-report.json || echo "No semgrep report generated"
              else
                echo "No files found for secret scanning"
              fi
            displayName: 'Secrets and Code Quality Scan (Semgrep)'
            continueOnError: true

          - task: PublishTestResults@2
            displayName: 'Publish Security Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/security-*.xml'
              mergeTestResults: true
              testRunTitle: 'Security Scan Results'
            condition: always()
            continueOnError: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Security Scan Reports (JSON)'
            inputs:
              pathToPublish: '$(System.DefaultWorkingDirectory)'
              artifactName: 'security-reports'
              publishLocation: 'Container'
            condition: always ( )
            continueOnError: true