# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
  - name: environments
    type: object
    default: ['DEV']
  - name: singleEnvironment
    default: 'false'
  - name: templateFolderName
    default: 'infra/bicep'
  - name: bicepVersion
    default: 'basic'
  - name: deploymentMode
    default: 'Incremental'
  - name: appsToDeploy
    default: 'none'
  - name: createResourceGroup
    default: true
  - name: publicAccessEnabled
    default: true
  - name: addRoleAssignments
    default: true
  - name: runGHASScan
    default: 'false'
  - name: runMSDevSecOpsScan
    default: 'false'
  - name: projectName
    default: ''
  - name: projectNumber
    default: ''

# ----------------------------------------------------------------------------------------------------
stages:
  # comment this if statement out if you want to use condition 1 and make the deploy wait for the scan
  - ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
      - stage: ScanApplication
        displayName: Scan Application
        jobs:
          - template: templates/scan-code-template.yml
            parameters:
              environmentCode: 'DEV'
              runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
              runGHASScan: ${{ parameters.runGHASScan }}

  # ----------------------------------------------------------------------------------------------------
  - ${{ each environmentCode in parameters.environments }}:
      - stage: CreateInfra${{ environmentCode }}
        # # Condition 1: wait for scan, proceed if:
        # #   a single environment is being deployed and scan is complete,
        # #   or the environment is 'dev', or if qa/prod, the previous stage (dev->qa or qa->prod) succeeded
        # condition: or(eq(${{ parameters.singleEnvironment }}, 'true'), and(eq(upper('${{ environmentCode }}'), 'DEV'), succeeded('ScanApplication')), and(eq(upper('${{ environmentCode }}'), 'QA'), succeeded('CreateInfraDEV')), and(eq(upper('${{ environmentCode }}'), 'PROD'), succeeded('CreateInfraQA')))
        # Condition 2: don't wait for scan, proceed if:
        #   the environment is 'dev', or if qa/prod, the previous stage (dev->qa or qa->prod) succeeded
        condition: or(eq(${{ parameters.singleEnvironment }}, 'true'), eq(upper('${{ environmentCode }}'), 'DEV'), and(eq(upper('${{ environmentCode }}'), 'QA'), succeeded('CreateInfraDEV')), and(eq(upper('${{ environmentCode }}'), 'PROD'), succeeded('CreateInfraQA')))
        displayName: Create ${{ environmentCode }} Resources
        jobs:
          - template: templates/create-infra-template.yml
            parameters:
              environmentCode: ${{ environmentCode }}
              templateFolderName: ${{ parameters.templateFolderName }}
              templateFileName: 'main-${{ parameters.bicepVersion }}.bicep'
              parameterFileName: 'main-${{ parameters.bicepVersion }}-azdo.bicepparam'
              createResourceGroup: ${{ parameters.createResourceGroup }}
              publicAccessEnabled: ${{ parameters.publicAccessEnabled }}
              createDnsZones: ${{ parameters.createDnsZones }}
              appsToDeploy: ${{ parameters.appsToDeploy }}
              addRoleAssignments: ${{ parameters.addRoleAssignments }}
              deploymentMode: ${{ parameters.deploymentMode }}
              projectName: ${{ parameters.projectName }}
              projectNumber: ${{ parameters.projectNumber }}
